# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_P_matrix <- function(x_target, x_support) {
    .Call(`_NaturalSpline_compute_P_matrix`, x_target, x_support)
}

compute_C_withoutTheta <- function(x_support) {
    .Call(`_NaturalSpline_compute_C_withoutTheta`, x_support)
}

compute_A_matrix <- function(x_target, x_support) {
    .Call(`_NaturalSpline_compute_A_matrix`, x_target, x_support)
}

ns_matrix <- function(x, m) {
    .Call(`_NaturalSpline_ns_matrix`, x, m)
}

